// export const SIGN_IN = 'SIGN_IN'
// export const SIGN_OUT = 'SIGN_OUT'
export const CREATE_FIELD = 'CREATE_FIELD'
export const FETCH_FIELDS = 'FETCH_FIELDS'
export const FETCH_FIELD = 'FETCH_FIELD'
export const DELETE_FIELD = 'DELETE_FIELD'
export const EDIT_FIELD = 'EDIT_FIELD'


export const CREATE_LOGIC = 'CREATE_LOGIC'
export const FETCH_LOGICS = 'FETCH_LOGICS'
export const FETCH_LOGIC = 'FETCH_LOGIC'
export const DELETE_LOGIC = 'DELETE_LOGIC'
export const EDIT_LOGIC = 'EDIT_LOGIC'

export const CREATE_RECORD = 'CREATE_RECORD'
export const FETCH_RECORDS = 'FETCH_RECORDS'
export const FETCH_RECORD = 'FETCH_RECORD'
export const EDIT_RECORD = 'EDIT_RECORD'
export const DELETE_RECORD = 'DELETE_RECORD'

export const CREATE_MAP = 'CREATE_MAP'
// export const FETCH_MAPS = 'FETCH_MAPS'
// export const FETCH_MAP = 'FETCH_MAP'
// export const EDIT_MAP = 'EDIT_MAP'
// export const DELETE_MAP = 'DELETE_MAP'